export const LOAD_MOVIES = 'LOAD_MOVIES';
export const CHANGE_DISPLAY_MODE = 'CHANGE_DISPLAY_MODE';
export const TOGGLE_FAVORITE_MOVIE = 'TOGGLE_FAVORITE_MOVIE';
export const ADD_REMINDER_MOVIES = 'ADD_REMINDER_MOVIES';